# Generated by Django 4.2.8 on 2023-12-28 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتياز'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', verbose_name='url  عنوان در '),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=300, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان محصول'),
        ),
    ]
