# Generated by Django 4.2.3 on 2023-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_products_ratings_products_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
