# Generated by Django 4.2.3 on 2023-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_products_ratings_remove_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', verbose_name='عنوان در url'),
        ),
    ]
