# Generated by Django 4.2.3 on 2024-01-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('size', models.CharField(max_length=100, verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'اطلاعات تگمیلی',
                'verbose_name_plural': 'لیست اطلاعات تگمیلی',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.productinformation', verbose_name='اطلاعات تگمیلی'),
        ),
    ]
